# Generated by Django 4.0.2 on 2022-02-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_post_code_order_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
